data/urls.py
from django.urls import path

from data import views

app_name = 'data'

urlpatterns = [
    path('products/',  views.Products.as_view(), name='products'),
    path('delete/',  views.ResetDB.as_view(), name='delete'),
]

home/urls.py
from django.urls import path

from home import views

app_name = 'home'

urlpatterns = [
    path('', views.index, name='index'),
    path('readme/', views.readme, name='readme')
]

large_files/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('upload/', include('upload.urls')),
    path('data/', include('data.urls')),
]

upload/urls.py
from django.urls import path

from upload import views

app_name = 'upload'

urlpatterns = [
    path('files/',  views.Files.as_view(), name='files'),
]

data/models.py
import uuid
from django.db import models

class Product(models.Model):
    name = models.CharField(max_length=420, null=True, blank=True)
    sku = models.CharField(max_length=120, primary_key=True)
    description = models.TextField(null=True, blank=True)

class ProductAggregate(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    name = models.CharField(max_length=420, null=True, blank=True)
    count = models.IntegerField(default=0)
    
class DatabaseAction(models.Model):
    name = models.CharField(max_length=420, null=True, blank=True)
    status = models.CharField(max_length=420, null=True, blank=True)
    time_started = models.DateTimeField(auto_now_add=True)
    last_updated = models.DateTimeField(auto_now=True)
    time_taken = models.FloatField(null=True, blank=True)
    

upload/models.py
from django.db import models

class FileItem(models.Model):
    name = models.CharField(max_length=120, null=True, blank=True)
    path = models.TextField(blank=True, null=True)
    size = models.BigIntegerField(default=0)
    file = models.FileField(upload_to='files/', null=True, blank=True)
    file_type = models.CharField(max_length=120, null=True, blank=True)
    timestamp = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    uploaded = models.BooleanField(default=False)
    active = models.BooleanField(default=True)
    processed = models.BooleanField(default=False)
    processing_time = models.CharField(max_length=120, null=True, blank=True)

    @property
    def title(self):
        return str(self.name)

data/views.py
from upload.models import FileItem
from django.http import JsonResponse
from django.forms import model_to_dict
from django.conf import settings

from rest_framework.views import APIView

from data.models import Product, ProductAggregate, DatabaseAction
from data.utils import ProcessCSV, start_data_aggregation, start_pandas_data_aggregation, start_thread_process, start_csv_processing
from braces.views import CsrfExemptMixin

class Products(CsrfExemptMixin, APIView):
        
    def get(self, request, *args, **kwargs):
        query = request.query_params.get('sku', False)
        ingest_query = request.query_params.get('ingest', False)
        if ingest_query:
            start_thread_process(start_csv_processing)
        try:
            product = Product.objects.get(sku=query)
        except:
            return JsonResponse({"status": "ok", "product": False}, status=200)
        return JsonResponse({"status": "ok", "product": model_to_dict(product)}, status=200)
    
    def post(self, request, *args, **kwargs):
        product_sku = request.data.get('product_sku', False)
        name = request.data.get('product_name', False)
        description = request.data.get('product_description', False)
        
        product = Product.objects.get(sku=product_sku)
        old_product_name = product.name
        product.name = name
        product.description = description
        product.save()
        if not(product.name == old_product_name):
            if not settings.DEBUG:
                start_thread_process(start_data_aggregation)
            else:
                start_thread_process(start_pandas_data_aggregation)
                
        return JsonResponse({"status": "ok", "product": model_to_dict(product)}, status=200)
    
    def delete(self, request, *args, **kwargs):
        product_sku = request.data.get('product_sku', False)
        product = Product.objects.get(sku=product_sku)
        product.delete()
        return JsonResponse({"status": "ok"}, status=200)

class DatabaseActions(CsrfExemptMixin, APIView):
    
    def get(self, request, *args, **kwargs):
        try:
            db = DatabaseAction.objects.all().values()
        except:
            return JsonResponse({"status": "ok", "db_actions": False}, status=200)
        return JsonResponse({"status": "ok", "db_actions": list(db)}, status=200)
    
    def post(self, request, *args, **kwargs):
        db_id = request.data.get('db_id', False)
        status = request.data.get('db_status', False)
        
        db = DatabaseAction.objects.get(id=db_id)
        db.status = status
        db.save()
        return JsonResponse({"status": "ok", "db": model_to_dict(db)}, status=200)

class ResetDB(CsrfExemptMixin, APIView):
    def get(self, request, *args, **kwargs):
        DatabaseAction.objects.all().delete()
        Product.objects.all().delete()
        ProductAggregate.objects.all().delete()
        FileItem.objects.all().delete()
        return JsonResponse({"status": "ok"}, status=200)

home/views.py
from django.core import paginator
from django.core.paginator import Paginator
from django.db.models import aggregates
from django.shortcuts import render
from django.conf import settings

from data.models import DatabaseAction, Product, ProductAggregate

def index(request):
    products_list = Product.objects.all().order_by('name')
    aggregate_list = ProductAggregate.objects.all().order_by('-count')[:15].values('name', 'count')
    paginator = Paginator(products_list, 10)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    prod = settings.DEBUG
    context = {
        'page_obj': page_obj,
        'count' : Product.objects.all().count(),
        'aggregate_table_count' : ProductAggregate.objects.all().count(),
        'aggregate_list': aggregate_list,
        'dbs': list(DatabaseAction.objects.all().values()),
        'in_prod': not(prod)
    }
    return render(request, 'home/index.html', context)

def readme(request):
    return render(request, 'home/readme.html')

upload/views.py
from django.http import JsonResponse

from rest_framework.views import APIView

from upload.utils import the_file_is_csv
from data.utils import modify_db_status, start_csv_processing, start_db_action, start_thread_process, time_this_function

from upload.models import FileItem
from braces.views import CsrfExemptMixin

import timeit

class Files(CsrfExemptMixin, APIView):
    
    def get(self, request, *args, **kwargs):
        files = list(FileItem.objects.all().values())
        return JsonResponse({"status": "ok", "files": files}, status=200)
    
    def post(self, request, *args, **kwargs):
        files = request.FILES.getlist('files[]')
        for file in files:
            if the_file_is_csv(file.name):
                f, file_uploaded = FileItem.objects.get_or_create(
                    name=file.name,
                    file=file,
                    file_type='csv'
                )
                if file_uploaded:
                    f.uploaded = True
                    f.save()
                    db_action = modify_db_status(db_action.id, "Completed")
        return JsonResponse({"status": "ok"}, status=200)
    
    def put(self, request, *args, **kwargs):
        start_csv_processing()
        return JsonResponse({"status": "ok"}, status=200)

home/templates/home/base.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="icon" type="image/png" href="https://st-ar.cdn.postman.com/images/favicon-1-16.png" sizes="16x16" nonce="">
    
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-F3w7mX95PdgyTmZZMECAngseQB83DfGTowi0iMjiWaeVhAn4FJkqJByhZMI3AhiU" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/jqueryui/1.12.1/jquery-ui.min.css" integrity="sha512-aOG0c6nPNzGk+5zjwyJaoRUgCdOrfSDhmMID2u4+OIslr0GjpLKo7Xm0Ao3xmpM4T8AmIouRkqwj1nrdVsLKEQ==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/blueimp-file-upload/10.32.0/css/jquery.fileupload.min.css" integrity="sha512-ETNxpham3n+DST8n2xV+sr8Dc2jYUBbQSwm86C5vJL4t2UJQ5cuPeP4pQqzry/9hS6Qlzul49BFDz1oWEC5e2w==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/blueimp-file-upload/10.32.0/css/jquery.fileupload-ui.min.css" integrity="sha512-Rlj0RFIHhpUPv4EZzRDhF/oFOPlsggW3VeCYaYqnDLvtgiVHf/jSsPE1DcIbEcwz4gbZs/piR4P9723el8dF5g==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    {% block my_css %}{% endblock my_css %}
    <title>Postman Upload Files</title>
  </head>
  <body>
    <nav class="navbar navbar-light bg-light">
      <div class="container-fluid">
        <a class="navbar-brand" href="#">
          <img src="https://res.cloudinary.com/postman/image/upload/t_team_logo/v1629869194/team/2893aede23f01bfcbd2319326bc96a6ed0524eba759745ed6d73405a3a8b67a8" alt="" width="30" height="24" class="d-inline-block align-text-top">
          Assignment <h6>by: Ishant Dahiya</h6>
        </a>
      
   
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="/">Home</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'home:readme' %}">Readme</a>
        </li>
      </ul>

      </div>
    </nav>
    {% block content %}
        
    {% endblock content %}

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-/bQdsTh/da6pkI1MST/rWKFNjaCP5gBSY4sEBT38Q/9RBh9AH40zEOg7Hlq2THRZ" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.6.0/jquery.min.js" integrity="sha512-894YE6QWD5I59HgZOGReFYm4dnWc1Qt5NtvYSaNcOP+u1T9qYdvdihz0PPSiiqn/+/3e7Jo4EaG7TubfWGUrMQ==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jqueryui/1.12.1/jquery-ui.min.js" integrity="sha512-uto9mlQzrs59VwILcLiRYeLKPPbS/bT71da/OEBYEwcdNUk8jYIy+D176RYoop1Da+f9mvkYrmj5MCLZWEtQuA==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/blueimp-file-upload/10.31.0/js/jquery.fileupload.min.js" integrity="sha512-qPkNWpUqYz8bhO5bGNPBvlCB9hPZBil2ez5Mo8yVmpCKI315UDDPQeg/TE7KwZ+U/wdSO8JguwVxYY/Ha7U+vQ==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
    <script>
      var tooltipTriggerList = [].slice.call(document.querySelectorAll('[data-bs-toggle="tooltip"]'))
      var tooltipList = tooltipTriggerList.map(function (tooltipTriggerEl) {
        return new bootstrap.Tooltip(tooltipTriggerEl)
      })
    </script>
    {% block my_js %}
        
    {% endblock my_js %}
  </body>
</html>

home/templates/home/index.html
{% extends "home/base.html" %}

{% load static %}

{% block my_css %}
    <link rel="stylesheet" href="{% static 'home/css/index.css' %}">
    <link rel="stylesheet" href="https://cdn.datatables.net/1.11.3/css/dataTables.bootstrap5.min.css">
{% endblock my_css %}

{% block content %}

<div class="container py-4">


    <div class="row mb-5 text-center">
    <div class="col-12 text-start">
        <h3>Actions and Stats:</h3>
    </div>
        <div class="col-3">
        
        {% if in_prod %}
            <button data-bs-toggle="tooltip" data-bs-placement="top" title="PySpark ingests CSV files and inserts into DB and aggregates it." type="button" class="btn btn-success" type="button" id="ingest">Load Data into DB</button>
        {% else %}
            <button data-bs-toggle="tooltip" data-bs-placement="top" title="Please use the docker commands to perform db operations." type="button" class="btn btn-success" type="button">Load Data into DB</button>
        {% endif %}
            
        </div>
        <div class="col-3">
            <button type="button" class="btn btn-danger" id="reset">Reset Database</button>
        </div>
        <div class="col-3">
            <button type="button" class="btn btn-info" id="update" data-bs-toggle="modal" data-bs-target="#exampleModal">Update Record by SKU</button>
        </div>
        <div class="col-3">
            <button type="button" class="btn btn-info" type="button" data-bs-toggle="offcanvas" data-bs-target="#offcanvasScrolling" aria-controls="offcanvasScrolling" id="view">View Stats</button>
        </div>
    </div>

    <div class="row my-5">
        <div class="col-12">
            <h3>
                Time taken for various queries and process:
            </h3>
        </div>
        <div class="dt">
            <table id="example" class="table table-striped" style="width:100%">
                <thead>
                    <tr>
                        <th>Process Name</th>
                        <th>Status</th>
                        <th>Time Started</th>
                        <th>Time Finished</th>
                        <th>Total Time Taken</th>
                    </tr>
                </thead>
                <tbody>
                    {% for d in dbs %}
                        <tr>
                            <td>{{d.name}}</td>
                            <td>{{d.status}}</td>
                            <td>{{d.time_started}}</td>
                            <td>{{d.last_updated}}</td>
                            <td>{{d.time_taken}}</td>
                        </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>

    <div class="row my-5">
        <div class="col-12">
            <h3>
                Products
            </h3>
            <div class="pages">
                <nav aria-label="Page navigation example">
                    <ul class="pagination">
                    {% if page_obj.has_previous %}
                        <li class="page-item"><a class="page-link" href="?page=1">First</a></li>
                        <li class="page-item"><a class="page-link" href="?page={{ page_obj.previous_page_number }}">Previous</a></li>
                    {% endif %}
                        <li class="page-item"><a class="page-link" href="#">Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}</a></li>
                    {% if page_obj.has_next %}
                        <li class="page-item"><a class="page-link" href="?page={{ page_obj.next_page_number }}">Next</a></li>
                        <li class="page-item"><a class="page-link" href="?page={{ page_obj.paginator.num_pages }}">Last</a></li>
                    {% endif %}
                    </ul>
                </nav>
            </div>
        </div>

        <div class="col-12">
            <table class="table">
                <thead>
                    <tr>
                        <th scope="col">Name</th>
                        <th scope="col">SKU</th>
                        <th scope="col">Description</th>
                    </tr>
                </thead>
                <tbody>
                    {% for product in page_obj %}
                        <tr>
                            <td>{{product.name}}</td>
                            <td>{{product.sku}}</td>
                            <td>{{product.description}}</td>
                        </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
</div>

<div class="offcanvas offcanvas-start" data-bs-scroll="true" data-bs-backdrop="false" tabindex="-1" id="offcanvasScrolling" aria-labelledby="offcanvasScrollingLabel">
  <div class="offcanvas-header">
    <h5 class="offcanvas-title" id="offcanvasScrollingLabel">Some quick stats about the DB</h5>
    <button type="button" class="btn-close text-reset" data-bs-dismiss="offcanvas" aria-label="Close"></button>
  </div>
  <div class="offcanvas-body">
    <ul>
        <li>Total Product Count : {{count}}</li>
        <li>Total Aggregate Table Count : {{aggregate_table_count}}</li>
    </ul>
    
    {% if aggregate_list %}        
        <h5 class="my-3">
            Users with most products (Top 15):
        </h5>
        <ul class="list-group">
            {% for user in aggregate_list %}
                <li class="list-group-item">{{user.name}} - {{user.count}} </li>
            {% endfor %}
        </ul>
    {% endif %}
        
    <hr>
    <h6 class="mt-5">By <a target="_blank" href="mailto:ishantdahiya@gmail.com">Ishant Dahiya</a> for Postman Data Engineer Position
    <br><br>
        <a target="_blank" href="https://github.com/ishantd/">
            <img height="32" width="32" src="https://cdn.jsdelivr.net/npm/simple-icons@v5/icons/github.svg" />
        </a>
    </h6>
  </div>
</div>

<!-- Edit Product Modal -->
<div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Search by SKU</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
      <div id="liveAlertPlaceholder"></div>
        <div class="input-group mb-3">
            <input type="text" class="form-control" name="product_sku" id="sku-search" placeholder="SKU">
            <button class="btn btn-primary" type="button" id="sku-search-button">Search</button>
        </div>
        <form action="{% url 'data:products' %}" method="post">
            <div class="mb-3">
                <label for="product_name" class="form-label">Name</label>
                <input type="text" class="form-control" id="product_name" name="product_name" placeholder="Name">
            </div>
            <div class="mb-3">
                <label for="product_description" class="form-label">Description</label> <br/>
                <textarea type="text" class="form-control"  id="product_description" placeholder="Description" name="product_description"></textarea>
            </div>
        </form>
        
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
        <button type="button" class="btn btn-primary" id="save-product">Save changes</button>
      </div>
    </div>
  </div>
</div>

{% endblock %}

{% block my_js %}
<script src="{% static 'home/js/index.js' %}"></script>
<script src="https://cdn.datatables.net/1.11.3/js/jquery.dataTables.min.js"></script>
<script src="https://cdn.datatables.net/1.11.3/js/dataTables.bootstrap5.min.js"></script>
{% endblock my_js %}